#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Installing fan controllers...\n"
sudo cp start-fan.py /usr/local/bin/
sudo cp stop-fan.py /usr/local/bin/
sudo chmod +x /usr/local/bin/start-fan.py
sudo chmod +x /usr/local/bin/stop-fan.py

echo "=> Starting fan controller...\n"
sudo cp fancontrol.sh /etc/init.d/
sudo chmod +x /etc/init.d/fancontrol.sh
sudo update-rc.d fancontrol.sh defaults
sudo /etc/init.d/fancontrol.sh start

echo "Fan controller installed."

echo "=> Installing shutdown listener...\n"
sudo cp listen-for-shutdown.py /usr/local/bin/
sudo chmod +x /usr/local/bin/listen-for-shutdown.py

echo "=> Starting shutdown listener...\n"
sudo cp listen-for-shutdown.sh /etc/init.d/
sudo chmod +x /etc/init.d/listen-for-shutdown.sh
sudo update-rc.d listen-for-shutdown.sh defaults
sudo /etc/init.d/listen-for-shutdown.sh start

echo "Shutdown listener installed.\n"
