#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Stopping shutdown listener...\n"
sudo update-rc.d listen-for-shutdown.sh remove
sudo /etc/init.d/listen-for-shutdown.sh stop

echo "=> Removing shutdown listener...\n"
sudo rm -rf /usr/local/bin/listen-for-shutdown.py 
sudo rm -rf /etc/init.d/listen-for-shutdown.sh 

echo "Shutdown listener uninstalled.\n"

echo "=> Stopping fan controller...\n"
sudo update-rc.d fancontrol.sh remove
sudo /etc/init.d/fancontrol.sh stop

echo "=> Removing fan controller...\n"
sudo rm -rf /usr/local/bin/start-fan.py 
sudo rm -rf /usr/local/bin/stop-fan.py 
sudo rm -rf /etc/init.d/fancontrol.sh 

echo "Fan controller uninstalled.\n"
